apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtrack-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Y-RyuZU/YouTrack.git'
    targetRevision: main
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: youtrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m